//! WP-0232: hashed-lockfile loader and `requirements.txt` renderer.
//!
//! Lockfiles are generated by `governance/scripts/lock_python_packs.ps1` from the
//! same pin set the runtime install applies, and committed to the repo at
//! `product/engine/resources/tooling/lockfiles/<pack>.lock.json`.
//!
//! At install time, the runtime renders the lockfile to a hashed `requirements.txt`
//! and runs `pip install --require-hashes --no-deps -r <tempfile>`. That eliminates
//! pip's resolver entirely (the source of WP-0231's class of bug).

use serde::Deserialize;
use std::path::Path;

#[derive(Debug, Clone, Deserialize)]
pub struct PythonLockfile {
    pub schema_version: u32,
    pub pack: String,
    #[serde(default)]
    pub generated_at_utc: String,
    #[serde(default)]
    pub pip_version: String,
    #[serde(default)]
    pub source_pins: Vec<String>,
    #[serde(default)]
    pub generator_notes: String,
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub sha256: Option<String>,
    #[serde(default)]
    pub requested: bool,
    #[serde(default)]
    pub is_direct: bool,
}

#[derive(Debug, thiserror::Error)]
pub enum LockfileError {
    #[error("lockfile not found at {path}")]
    NotFound { path: String },
    #[error("failed to read lockfile {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to parse lockfile {path}: {source}")]
    Parse {
        path: String,
        #[source]
        source: serde_json::Error,
    },
    #[error(
        "lockfile {pack} contains {missing_count} package(s) without a sha256 hash; \
         --require-hashes cannot proceed. First offender: {first_name}=={first_version}"
    )]
    MissingHashes {
        pack: String,
        missing_count: usize,
        first_name: String,
        first_version: String,
    },
}

impl PythonLockfile {
    pub fn load(path: &Path) -> Result<Self, LockfileError> {
        let display = path.to_string_lossy().into_owned();
        if !path.exists() {
            return Err(LockfileError::NotFound { path: display });
        }
        let text = std::fs::read_to_string(path).map_err(|e| LockfileError::Io {
            path: display.clone(),
            source: e,
        })?;
        serde_json::from_str(&text).map_err(|e| LockfileError::Parse {
            path: display,
            source: e,
        })
    }

    /// Parse a lockfile already loaded from memory (e.g. via `include_str!`).
    /// This is the runtime-canonical path used by `bundled_lockfile_for_pack` so end-user
    /// installs never depend on the lockfile JSON existing on disk next to the exe.
    pub fn from_bundled_str(pack_name: &str, text: &str) -> Result<Self, LockfileError> {
        serde_json::from_str(text).map_err(|e| LockfileError::Parse {
            path: format!("<bundled:{pack_name}>"),
            source: e,
        })
    }
}

// WP-0232 (shipping fix): bundle every committed lockfile into the engine binary at
// compile time. `env!("CARGO_MANIFEST_DIR")` resolves on the build machine, but
// `include_str!` reads the file content at compile time and bakes it into the binary,
// so the resulting bytes are available on every end-user install regardless of where
// the exe lives. Pack names here must match the keys in
// `pinned_dependency_manifest.json :: lockfiles` and the file paths must match the
// values there. The `parses_real_lockfile_from_resources` test guards against drift.
const LOCKFILE_DEMUCS: &str = include_str!("../resources/tooling/lockfiles/demucs.lock.json");
const LOCKFILE_DIARIZATION: &str =
    include_str!("../resources/tooling/lockfiles/diarization.lock.json");
const LOCKFILE_TTS_PREVIEW: &str =
    include_str!("../resources/tooling/lockfiles/tts_preview.lock.json");
const LOCKFILE_TTS_NEURAL_LOCAL_V1: &str =
    include_str!("../resources/tooling/lockfiles/tts_neural_local_v1.lock.json");
const LOCKFILE_TTS_VOICE_PRESERVING_LOCAL_V1: &str =
    include_str!("../resources/tooling/lockfiles/tts_voice_preserving_local_v1.lock.json");

/// Returns the bundled lockfile body for the given pack, or `None` if no lockfile is
/// bundled for it (e.g. spleeter — see WP-0232 notes for the manifest defect).
pub fn bundled_lockfile_for_pack(pack_name: &str) -> Option<&'static str> {
    match pack_name {
        "demucs" => Some(LOCKFILE_DEMUCS),
        "diarization" => Some(LOCKFILE_DIARIZATION),
        "tts_preview" => Some(LOCKFILE_TTS_PREVIEW),
        "tts_neural_local_v1" => Some(LOCKFILE_TTS_NEURAL_LOCAL_V1),
        "tts_voice_preserving_local_v1" => Some(LOCKFILE_TTS_VOICE_PRESERVING_LOCAL_V1),
        _ => None,
    }
}

impl PythonLockfile {
    /// Render the lockfile to a `requirements.txt` body suitable for
    /// `pip install --require-hashes --no-deps -r <file>`.
    ///
    /// Errors if any package is missing a sha256 (pip refuses --require-hashes on a
    /// partially-hashed file, so we fail loudly here instead of letting pip do it).
    pub fn render_hashed_requirements(&self) -> Result<String, LockfileError> {
        let missing: Vec<&LockedPackage> = self
            .packages
            .iter()
            .filter(|p| p.sha256.as_deref().map(str::is_empty).unwrap_or(true))
            .collect();
        if let Some(first) = missing.first() {
            return Err(LockfileError::MissingHashes {
                pack: self.pack.clone(),
                missing_count: missing.len(),
                first_name: first.name.clone(),
                first_version: first.version.clone(),
            });
        }

        let mut out = String::new();
        out.push_str(&format!(
            "# auto-generated from {} (WP-0232). Do not edit by hand.\n",
            self.pack
        ));
        for pkg in &self.packages {
            // sha256 presence is guaranteed by the check above.
            let sha = pkg.sha256.as_deref().unwrap_or("");
            out.push_str(&format!(
                "{}=={} --hash=sha256:{}\n",
                pkg.name, pkg.version, sha
            ));
        }
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> PythonLockfile {
        PythonLockfile {
            schema_version: 1,
            pack: "test_pack".to_string(),
            generated_at_utc: "2026-05-18T00:00:00Z".to_string(),
            pip_version: "26.1.1".to_string(),
            source_pins: vec!["foo==1.0".to_string()],
            generator_notes: String::new(),
            packages: vec![
                LockedPackage {
                    name: "foo".to_string(),
                    version: "1.0".to_string(),
                    url: Some("https://example.com/foo-1.0.whl".to_string()),
                    sha256: Some("a".repeat(64)),
                    requested: true,
                    is_direct: false,
                },
                LockedPackage {
                    name: "bar".to_string(),
                    version: "2.3".to_string(),
                    url: Some("https://example.com/bar-2.3.whl".to_string()),
                    sha256: Some("b".repeat(64)),
                    requested: false,
                    is_direct: false,
                },
            ],
        }
    }

    #[test]
    fn render_emits_hashed_requirements_lines() {
        let lock = fixture();
        let rendered = lock.render_hashed_requirements().expect("should render");
        assert!(rendered.contains(&format!("foo==1.0 --hash=sha256:{}", "a".repeat(64))));
        assert!(rendered.contains(&format!("bar==2.3 --hash=sha256:{}", "b".repeat(64))));
        assert!(rendered.starts_with("# auto-generated from test_pack"));
    }

    #[test]
    fn render_fails_when_a_package_has_no_hash() {
        let mut lock = fixture();
        lock.packages[1].sha256 = None;
        let err = lock
            .render_hashed_requirements()
            .expect_err("should reject unhashed package");
        match err {
            LockfileError::MissingHashes {
                missing_count,
                first_name,
                ..
            } => {
                assert_eq!(missing_count, 1);
                assert_eq!(first_name, "bar");
            }
            other => panic!("expected MissingHashes, got {other:?}"),
        }
    }

    #[test]
    fn render_fails_when_a_package_has_empty_hash() {
        let mut lock = fixture();
        lock.packages[0].sha256 = Some(String::new());
        let err = lock
            .render_hashed_requirements()
            .expect_err("should reject empty hash");
        assert!(matches!(err, LockfileError::MissingHashes { .. }));
    }

    #[test]
    fn every_manifest_lockfile_has_a_bundled_entry() {
        // WP-0232 shipping fix: the runtime path is `bundled_lockfile_for_pack`. If a
        // pack is in the manifest's `lockfiles` map but not bundled here, end-user
        // installs silently fall through to the legacy pinned-list path and lose the
        // --require-hashes guarantee. This test catches that drift at compile time.
        use crate::pinned_dependency_manifest;
        let manifest = pinned_dependency_manifest::manifest();
        for pack_name in manifest.lockfiles.keys() {
            let bundled = bundled_lockfile_for_pack(pack_name);
            assert!(
                bundled.is_some(),
                "pack {pack_name} is in manifest.lockfiles but has no bundled entry in python_lockfile.rs"
            );
            // And the bundled content must parse and render.
            let lock = PythonLockfile::from_bundled_str(pack_name, bundled.unwrap())
                .unwrap_or_else(|e| {
                    panic!("bundled lockfile for {pack_name} failed to parse: {e}")
                });
            assert_eq!(lock.pack, *pack_name);
            let _ = lock.render_hashed_requirements().unwrap_or_else(|e| {
                panic!("bundled lockfile for {pack_name} failed to render: {e}")
            });
        }
    }

    #[test]
    fn parses_real_lockfile_from_resources() {
        // Smoke-test: every lockfile committed under resources/tooling/lockfiles/ parses
        // and renders without error. Catches schema drift between the generator and the
        // loader. Uses the manifest's `lockfiles` map as the source of truth so adding a
        // new lockfile to the manifest also adds it to this test.
        use crate::pinned_dependency_manifest;
        let manifest = pinned_dependency_manifest::manifest();
        assert!(
            !manifest.lockfiles.is_empty(),
            "expected at least one pack lockfile to be registered"
        );
        for (pack_name, relative_path) in &manifest.lockfiles {
            let abs = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("resources")
                .join("tooling")
                .join(relative_path);
            let lock = PythonLockfile::load(&abs).unwrap_or_else(|e| {
                panic!(
                    "lockfile for {pack_name} at {} failed to load: {e}",
                    abs.display()
                )
            });
            assert_eq!(
                lock.pack, *pack_name,
                "lockfile pack name should match map key"
            );
            assert!(
                !lock.packages.is_empty(),
                "lockfile for {pack_name} should contain packages"
            );
            let _ = lock
                .render_hashed_requirements()
                .unwrap_or_else(|e| panic!("lockfile for {pack_name} failed to render: {e}"));
        }
    }
}
